#!/bin/bash
#Aidan Polese - 10197342

passReq=0

#The password is read in and the rules for the password are also displayed
echo "This is a password checker tool. It will tell you the strength of a password based on certain criteria"
echo "-The password must be at least 8 characters long"
echo "-The password must contain at least one numeric character"
echo "-The password must contai at least one of the following characters: @,#,$,%,&,*,+,-,="
echo ""

read -p "Please enter your desired password: " -s pass

#Checks the lenght requirement
if [ ${#pass} -ge 8 ]; then
	((passReq+=1))
fi

#Looks for numbers in the password
if echo $pass | grep '[0-9]' >/dev/null; then
	((passReq+=1))
fi

#looks for the special symbols in the password
if echo $pass | grep '[@#$%&*+-=]' >/dev/null; then
	((passReq+=1))
fi

echo " "

#based on what requirments are met will print out the password strength
if [ $passReq == 1 ]; then
	echo "Password strength: Weak"
elif [ $passReq == 2 ]; then
	echo "Password strength: Moderate"
elif [ $passReq == 3 ]; then
	echo "Password strength: Strong"
else
	echo "No requirements met"
fi
